ENVIRONMENT = "development"

# Server Configuration
[SERVER]
ADDRESS = ":8080"
BASE_PATH = "/hr/api"
READ_TIMEOUT = 30
WRITE_TIMEOUT = 30

# Database Configuration
[DATABASE]
HOST = "localhost"
PORT = "5432"
USER = "postgres"
PASSWORD = "123"
NAME = "hr_db_dev"
#SSL_MODE = "require"
MAX_OPEN_CONNS = 50
MAX_IDLE_CONNS = 10
CONN_MAX_LIFETIME = 300

# JWT Configuration
[JWT]
SECRET = "my-secret"
EXPIRY_HOURS = 24
[STORAGE]
UPLOAD_PATH = "/app/storage/uploads"
MAX_FILE_SIZE = 10485760
PUBLIC_URL = "https://localhost:8080/hr/api/uploads/"

[STORAGE.EMPLOYEES]
MAX_SIZE = 5242880
ALLOWED_TYPES = ["image/jpeg", "image/jpg", "image/png"]
SUBDIRECTORY = "employees"

[CORS]
ALLOWED_ORIGINS = ["https://hr-api.com", "https://www.hr-api.com"]
ALLOWED_METHODS = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
ALLOWED_HEADERS = ["Content-Type", "Authorization"]
ALLOW_CREDENTIALS = true